# Update this when adding a new AndroidManifest.xml.
LOCAL_AAPT_FLAGS := \
	com.android.assets.product \
	com.android.assets.quantum \
	com.android.bubble \
	com.android.contacts.common \
	com.android.dialer2.about \
	com.android.dialer2.app \
	com.android.dialer2.app.manifests.activities \
	com.android.dialer2.assisteddialing \
	com.android.dialer2.assisteddialing.ui \
	com.android.dialer2.backup \
	com.android.dialer2.binary.aosp.testing \
	com.android.dialer2.binary.google \
	com.android.dialer2.blocking \
	com.android.dialer2.blockreportspam \
	com.android.dialer2.callcomposer \
	com.android.dialer2.callcomposer.camera \
	com.android.dialer2.callcomposer.camera.camerafocus \
	com.android.dialer2.callcomposer.cameraui \
	com.android.dialer2.calldetails \
	com.android.dialer2.calllog.database \
	com.android.dialer2.calllog.ui \
	com.android.dialer2.calllog.ui.menu \
	com.android.dialer2.calllogutils \
	com.android.dialer2.clipboard \
	com.android.dialer2.commandline \
	com.android.dialer2.common \
	com.android.dialer2.configprovider \
	com.android.dialer2.contactphoto \
	com.android.dialer2.contactsfragment \
	com.android.dialer2.databasepopulator \
	com.android.dialer2.dialpadview \
	com.android.dialer2.enrichedcall.simulator \
	com.android.dialer2.feedback \
	com.android.dialer2.glidephotomanager.impl \
  com.android.dialer2.historyitemactions \
	com.android.dialer2.interactions \
	com.android.dialer2.lettertile \
	com.android.dialer2.location \
	com.android.dialer2.main.impl \
	com.android.dialer2.main.impl.toolbar \
	com.android.dialer2.main.impl.bottomnav \
	com.android.dialer2.notification \
	com.android.dialer2.oem \
	com.android.dialer2.phonelookup.database \
	com.android.dialer2.phonenumberutil \
	com.android.dialer2.postcall \
	com.android.dialer2.precall.impl \
	com.android.dialer2.precall.externalreceiver \
	com.android.dialer2.preferredsim.impl \
	com.android.dialer2.searchfragment.common \
	com.android.dialer2.searchfragment.cp2 \
	com.android.dialer2.searchfragment.directories \
	com.android.dialer2.searchfragment.list \
	com.android.dialer2.searchfragment.nearbyplaces \
	com.android.dialer2.searchfragment.remote \
	com.android.dialer2.shortcuts \
	com.android.dialer2.simulator.impl \
	com.android.dialer2.speeddial \
	com.android.dialer2.theme \
	com.android.dialer2.util \
	com.android.dialer2.voicemail.listui \
	com.android.dialer2.voicemail.listui.error \
	com.android.dialer2.voicemail.listui.menu \
	com.android.dialer2.voicemail.settings \
	com.android.dialer2.voicemailstatus \
	com.android.dialer2.widget \
	com.android.incallui \
	com.android.incallui.answer.impl.affordance \
	com.android.incallui.answer.impl \
	com.android.incallui.answer.impl.answermethod \
	com.android.incallui.answer.impl.hint \
	com.android.incallui.audioroute \
	com.android.incallui.autoresizetext \
	com.android.incallui.calllocation.impl \
	com.android.incallui.callpending \
	com.android.incallui.commontheme \
	com.android.incallui.contactgrid \
	com.android.incallui.disconnectdialog \
	com.android.incallui.hold \
	com.android.incallui.incall.impl \
	com.android.incallui.maps.impl \
	com.android.incallui.rtt.impl \
	com.android.incallui.rtt.protocol \
  com.android.incallui.speakeasy \
	com.android.incallui.sessiondata \
	com.android.incallui.spam \
	com.android.incallui.speakerbuttonlogic \
	com.android.incallui.telecomeventui \
	com.android.incallui.video.impl \
	com.android.incallui.video.protocol \
	com.android.phoneapphelper \
	com.android.voicemail \
	com.android.voicemail.impl \
	com.android.voicemail.impl.configui \
